name: bookstack
services:
  wiki_db:
    container_name: wiki_db
    image: mysql:5.7
    env_file: .env
    restart: always
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./database/data:/var/lib/mysql
    extra_hosts:
      - host.docker.internal:host-gateway

  wiki_app:
    container_name: wiki_app
    image: solidnerd/bookstack:25.2
    env_file: .env
    depends_on:
      - wiki_db
    restart: always
    environment:
      - DB_HOST=wiki_db:3306
      - APP_LANG=es_AR
      - APP_THEME=custom
      # - ALLOWED_IFRAME_HOSTS="*"
      # - ALLOWED_IFRAME_SOURCES="*"
    ports:
      - ${WIKI_PORT}:8080
    volumes:
      - ./bookstack/public/uploads:/var/www/bookstack/public/uploads
      - ./bookstack/storage/uploads:/var/www/bookstack/storage/uploads
      - ./themes:/var/www/bookstack/themes
    extra_hosts:
      - host.docker.internal:host-gateway
