name: wikijs
services:
  wiki_app:
    container_name: wiki_app
    image: ghcr.io/requarks/wiki:2
    env_file: .env
    restart: always
    ports:
      - ${WIKI_PORT}:3000
    extra_hosts:
      - host.docker.internal:host-gateway
